import os
Import('env')
Import('cuda_env')
eco_src = Split('''
	Filter_set.cpp
	Test_filter.cpp
	Filter.cpp 
	Genome.cpp 
	Creature.cpp 
	probability.cpp
	Population.cpp
	Data_set.cpp
	Eco_options.cpp
	Adaboost_model.cpp
	Random_forest.cpp
	Tree.cpp
	Tree_node.cpp
	''')
cuda_src = 'Gpu_filter.cu'

obj = env.Object(eco_src)
cuda_obj = cuda_env.Object(cuda_src)
obj = obj + cuda_obj

env.Program('#bin/eco_train', ['eco_train.cpp'] + obj)
env.Program('#bin/eco_test', ['eco_test.cpp'] + obj)
env.Program('#bin/eco_single_predict', ['eco_single_predict.cpp'] + obj)
env.Program('#bin/core_test', ['core_test.cpp'] + obj)

Return('obj')